### ISSUE TITLE
Sandbox mode should make it clear that edits don't stick

### ISSUE THREAD

**Issue by lee-feigenbaum** [salsify/safer_rails_console#19]
Currently, other than the text that indicates you're in sandbox mode, you get no indication that edits won't stick. All operations succeed as if an edit was made successfully, including reloading objects. This has lead to multiple cases across multiple people of believing that changes were made successfully when they were not, causing inaccurate communications back to customers, customer frustration, and loss of time.

Examples include a variety of updates I've made for customer support issues to disable import schedules and re-organize catalog filters. 

I believe that @jredburn hit something similar, and know that @brea9482 did as well.

Most recently, I believe @mattcross hit this when trying to DQ scheduled events to have a controlled restart of the events when we were having issues with the scheduler. The DQ'ed events were not actually DQ'ed and ran when the scheduler was restarted when we weren't intending that.

I consider this a high priority issue to resolve to make sandbox mode usable.

/cc @timothysu @fgarces

**Comment by timothysu** [comment]
Would it help to have messaging after each modify/write operation in sandbox mode?

**Comment by lee-feigenbaum** [comment]
Yes, I think so. The messages would need to be obvious and only for modifications, because otherwise we'd quickly learn to ignore them (as we're already subconsciously doing with the "sandboxed" notification text)

**Comment by jturkel** [comment]
What about using the colorization to indicate read-only/read+write rather than the environment?

**Comment by timothysu** [comment]
@jredburn suggested that the most helpful thing would be a reminder on non-read operations while in sandbox mode.

**Comment by timothysu** [comment]
@jturkel if additional messaging is the solution, should that messaging be done on assignment vs DB write?  for example, should calling `.update`, `Object.attribute = x`, etc. be blocked/trigger a message.  or should that be done when `.save` is called?

**Comment by jturkel** [comment]
If you switch to using read-only DB connections will the DB fail queries making this issue moot? Trying to get cute in the Rails layer will be far from perfect e.g. to do it reliably you'd have handle calls to Connection#execute and interpret the SQL which is probably not a game we want to get into.

**Comment by jredburn** [comment]
That seems ideal to me if we can just get the DB to enforce it, and maybe
down the road layer in things like preventing search index destruction, etc.

**Comment by timothysu** [comment]
A PR has been opened for this ( #21 ).  I'd appreciate any feedback regarding user messaging when an operation is rejected due to the read-only DB connection.  See the PR for more details.
