### ISSUE TITLE
safer_rails_console breaks newrelic reporting

### ISSUE THREAD

**Issue by Tongboy** [salsify/safer_rails_console#23]
Hi,

I know this is an odd one...

Dig the idea, implemented it on friday, worked great - realized earlier today that after deployment to prod/staging that newrelic stopped reporting.

reverted gem installation & boot.rb change and newrelic reporting was back up and working.

I can reproduce reliably in my dev environment - newrelic_apm 4.5.x & 4.8.x both have same issue. using safer_rails_console 0.2.0

I don't even know where to start debugging this one - if anyone can throw pointers at me I'm happy to dig in to it myself.

thank you!

**Comment by beansupreme** [comment]
I've been using New Relic Ruby APM 6.1.0, and safer_rails_console 0.2.0 and haven't seen any issues. Reporting still seems to be working as it was before installing the gem.

**Comment by Tongboy** [comment]
I'm no longer with that project so I'll go ahead and close this - I never got around to looking in to the issue again or reinstalling safer_rails_console - bummer too, was looking at dummy proofing prod a bit.
