### ISSUE TITLE
No default settings for rails 5.1 and 5.2

### ISSUE THREAD

**Issue by gdomingu** [salsify/safer_rails_console#29]
Hi there. 
It seems that the default settings aren't getting properly set to the app configuration. I've tried this with Rails 5.1.7 and Rails 5.2.4.1.

```
Rails.application.config.safer_rails_console
=> {}

SaferRailsConsole.config
=> #<SaferRailsConsole::Configuration:0x00007ff424d60ea0 @_config={}>

SaferRailsConsole::Configuration.config
=> {:console=>"irb", :environment_names=>{"development"=>"dev", "staging"=>"staging", "production"=>"prod"}, :environment_prompt_colors=>{"development"=>32, "staging"=>33, "production"=>31}, :sandbox_environments=>["production"], :sandbox_prompt=>false, :warn_environments=>["production"], :warn_text=>"WARNING: YOU ARE USING RAILS CONSOLE IN PRODUCTION!\nChanging data can cause serious data loss. Make sure you know what you're doing."}
```

When I add config to application.rb it does show up in `Rails.application.config.safer_rails_console`. 

Thank you.

**Comment by jturkel** [comment]
The configuration defaulting is applied lazily in `SaferRailsConsole.config` via `ActiveSupport::Configurable` which is why you're not seeing any values e.g.

```ruby
test-app(dev)(writable):006:0> SaferRailsConsole.config
=> #<SaferRailsConsole::Configuration:0x00007fe7ce21da28 @_config={}>

test-app(dev)(writable):007:0> SaferRailsConsole.config.environment_names
=> {"development"=>"dev", "staging"=>"staging", "production"=>"prod"}
```
 
This is expected. Are you seeing any issues with sandboxing not working properly in your applications?

**Comment by gdomingu** [comment]
@jturkel ah I see. Yes, I needed add 
`config.safer_rails_console.sandbox_environments = %w{production}` to my production.rb because it wasn't sandboxing. But I can't recreate it now. Thanks for your reply.
